language: php

sudo: false

services:
  - mysql

php:
  - 7.0
  - 7.1

install:
  - composer self-update
  - composer install --prefer-dist

before_script:
  - mysql -e 'create database tools_ci_test;'

script:
  - phpunit --coverage-text

notifications:
  email: false
