language: php

sudo: false

cache:
  directory:
    - $HOME/.composer/cache

services:
  - mysql

php:
  - 7.0
  - 7.1

install:
  - composer install --prefer-dist

before_script:
  - mysql -e 'create database tools_ci_test;'

script:
  - phpunit --coverage-text
  - vendor/bin/php-cs-fixer --diff --dry-run --verbose fix

notifications:
  email: false
